### ISSUE TITLE
Run NotificationListenerService Background

### ISSUE THREAD

**Issue by smurat** [PavieOlivier/AndroidNotificationListener#7]
hi. i want to listen incoming notifications and save them to db in my project.
package works great  if user doesnt quit app or remove the app from recent apps..
I dont know to much kotlin and java. But is it  possible to run notifitionlistenerservice run background with dart code and save notifications to database with hive or sqflite?

**Comment by PavieOlivier** [comment]
Hello, 
Thank you for using my package.
I am sorry but I did not code the package this way, the application needs to be open in order to receive and manage notifications. 

What you are requesting needs a special type of service in Android called "**sticky services**". These services run in the background irrespective of the application state (open or close) . These services start (and restart) automatically.

However in flutter, I do not know how to achieve this easily and facilitate the communication between the dart code and the native one in a closed state... 

Your best bet at this point will be to go fully native (on Android since iOS doesn't allow apps to read notifications )
